name: Deploy Vite React App to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  

      - name: Install Dependencies
        run: npm install

      - name: Build Vite React App
        run: npm run build  

      - name: List Files (Debugging Step)
        run: ls -la 

      - name: Verify Build Directory (Debugging Step)
        run: ls -la dist  

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  
          folder: dist  
